const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true});try{
 const page=await browser.newPage({viewport:{width:1100,height:800}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:18765');await page.locator('#login-form [name=password]').fill('browser-test-password');await page.locator('#login-form [type=submit]').click();await page.locator('#session').waitFor({state:'visible'});
 await page.evaluate(async()=>{const response=await fetch('/api/documents/draft-mariadb-workspace',{method:'PUT',headers:{'Content-Type':'application/json','If-Match':''},body:JSON.stringify({tabs:Array.from({length:12},(_,i)=>({name:i===11?'New Query':'Insert Row',sql:'SELECT '+i+' AS legacy_value;'})),active:0})});if(!response.ok)throw Error('Could not seed legacy workspace');Win2kShell.actions.databaseLegacy();});
 const w=page.locator('.database-window'),tabs=w.locator('.db-tabs [role=tab]'),editor=w.locator('.db-sql');
 async function menu(group,label){await w.getByRole('menuitem',{name:group,exact:true}).click();await page.getByRole('menuitem',{name:label,exact:true}).click();}
 await page.waitForFunction(()=>document.querySelectorAll('.db-tabs [role=tab]').length===12);assert.equal(await editor.inputValue(),'SELECT 0 AS legacy_value;');assert.equal(await w.getByLabel('Open queries').locator('option').count(),12);
 await menu('File','New Query');for(let i=0;i<6;i++)await w.getByRole('button',{name:'New Query',exact:true}).click();assert.equal(await tabs.count(),13);await editor.fill('SELECT 999 AS unique_value;');
 page.once('dialog',d=>d.dismiss());await w.getByRole('button',{name:'Close Insert Row · 2',exact:true}).click();assert.equal(await tabs.count(),13);
 page.once('dialog',d=>d.accept());await w.getByRole('button',{name:'Close Insert Row · 2',exact:true}).click();await page.waitForFunction(()=>document.querySelectorAll('.db-tabs [role=tab]').length===12);assert.equal(await editor.inputValue(),'SELECT 999 AS unique_value;');
 await page.setViewportSize({width:600,height:700});await page.evaluate(()=>document.documentElement.style.setProperty('--personal-font-size','18px'));await w.locator('[data-control=max]').click();
 const strip=await w.locator('.db-query-strip').boundingBox(),code=await editor.boundingBox(),results=await w.locator('.db-results').boundingBox();assert(strip.height<=54,JSON.stringify(strip));assert(code.height>=80);assert(results.height>=90);await w.getByLabel('Open queries').selectOption('0');assert.equal(await editor.inputValue(),'SELECT 0 AS legacy_value;');await page.screenshot({path:'/tmp/pi2000-many-queries-small.png'});
 page.once('dialog',d=>d.accept());await menu('Query','Close Other Queries');await page.waitForFunction(()=>document.querySelectorAll('.db-tabs [role=tab]').length===1);await w.locator('.app-status').filter({hasText:'SQL workspace saved'}).waitFor();await page.reload();await page.waitForFunction(()=>document.querySelector('.db-sql')?.value==='SELECT 0 AS legacy_value;');assert.equal(await tabs.count(),1);
 page.once('dialog',d=>d.accept());await menu('Query','Close All Queries');await page.waitForFunction(()=>document.querySelector('.db-sql').value==='');assert.equal(await tabs.count(),1);
 await page.setViewportSize({width:1100,height:800});await page.evaluate(()=>document.documentElement.style.setProperty('--personal-font-size','13px'));
 for(let i=0;i<32;i++){await editor.fill('SELECT '+i+' AS value;');if(i<31)await w.getByRole('button',{name:'New Query',exact:true}).click();}
 await w.getByRole('button',{name:'New Query',exact:true}).click();const manager=page.locator('dialog.db-dialog');await manager.getByRole('button',{name:'Close Selected'}).waitFor();assert.equal(await tabs.count(),32);await manager.locator('input[type=checkbox]').first().check();page.once('dialog',d=>d.accept());await manager.getByRole('button',{name:'Close Selected'}).click();await manager.waitFor({state:'detached'});assert.equal(await tabs.count(),31);
 page.once('dialog',d=>d.accept());await menu('Query','Close All Queries');await page.waitForFunction(()=>document.querySelector('.db-sql').value==='');
 if(process.env.WIN2K_TEST_DB_PORT){
  await menu('File','New Connection');const form=page.locator('dialog.db-dialog');await form.locator('[name=name]').fill('Workspace fixture');await form.locator('[name=username]').fill('root');await form.locator('[name=port]').fill(process.env.WIN2K_TEST_DB_PORT);await form.locator('[name=tls]').selectOption('disabled');await form.locator('[name=save_password]').check();await form.getByRole('button',{name:'OK',exact:true}).click();await form.waitFor({state:'detached'});await w.getByRole('button',{name:'Connect',exact:true}).click();await w.locator('.db-context').filter({hasText:'Workspace fixture'}).waitFor();
  await editor.fill('SELECT 101 AS first_result;');await w.getByRole('button',{name:'Execute',exact:true}).click();await w.locator('.db-results').filter({hasText:'first_result'}).waitFor();await w.getByRole('button',{name:'New Query',exact:true}).click();assert(!(await w.locator('.db-results').textContent()).includes('first_result'));
  await editor.fill('SELECT 202 AS second_result;');await w.getByRole('button',{name:'Execute',exact:true}).click();await w.locator('.db-results').filter({hasText:'second_result'}).waitFor();await w.getByLabel('Open queries').selectOption('0');await w.locator('.db-results').filter({hasText:'first_result'}).waitFor();assert(!(await w.locator('.db-results').textContent()).includes('second_result'));
  await editor.fill('CREATE DATABASE workspace_suite; USE workspace_suite; CREATE TABLE example (id INT AUTO_INCREMENT PRIMARY KEY, note VARCHAR(60), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);');await w.getByRole('button',{name:'Execute',exact:true}).click();await w.locator('.db-messages').filter({hasText:'Completed in'}).waitFor();await menu('View','Refresh Objects');await w.locator('[data-object=example]').click();assert.equal(await editor.isVisible(),false);assert.equal(await w.locator('.db-query-strip').isVisible(),false);const before=await tabs.count();
  for(let i=0;i<3;i++){await w.locator('.db-data-actions').getByRole('button',{name:'Insert Row',exact:true}).click();const row=page.locator('dialog.db-dialog');await row.locator('[name=value-1]').fill('Direct row '+i);await row.getByRole('button',{name:'OK',exact:true}).click();await row.waitFor({state:'detached'});await page.waitForFunction(n=>document.querySelectorAll('.db-results tbody tr').length===n,i+1);await w.locator('.db-messages').filter({hasText:'Row inserted'}).waitFor();}
  assert.equal(await tabs.count(),before);assert.equal(await w.locator('.db-results tbody tr').count(),3);await page.screenshot({path:'/tmp/pi2000-table-workspace.png'});
  await w.getByRole('button',{name:'SQL Queries',exact:true}).click();assert.equal(await editor.isVisible(),true);await editor.fill('DROP DATABASE workspace_suite');await w.getByRole('button',{name:'Execute',exact:true}).click();await w.locator('.db-messages').filter({hasText:'Completed in'}).waitFor();
 }
 assert.deepEqual(errors,[]);console.log('PASS: restored legacy queries, single-line overflow at 18px/600px, close/cancel/bulk/persistence, empty-tab reuse, 32-tab recovery, per-query results and direct table operations');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
