const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),{command}=require('./classic_helpers.cjs');
(async()=>{
 let installed=null;if(process.env.PI2000_UTILITIES_INSTALLED_TEST==='1'){let input='';for await(const chunk of process.stdin)input+=chunk;installed=JSON.parse(input);}
 const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true});
 try{
 const context=await browser.newContext({viewport:{width:1400,height:1000},ignoreHTTPSErrors:!!installed});
 if(installed)await context.addCookies([{name:installed.cookie,value:installed.token,url:installed.origin,secure:true,httpOnly:true,sameSite:'Strict'}]);
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());page.setDefaultTimeout(15000);
 await page.goto(installed?.origin||'http://127.0.0.1:18765');if(!installed){await page.locator('#login-form [name=password]').fill('browser-test-password');await page.locator('#login-form [type=submit]').click();}await page.locator('#session').waitFor({state:'visible'});
 await page.locator('#desktop-icons [data-action=displaystudio]').click();let menuWindow=page.locator('.display-window');await menuWindow.getByRole('menuitem',{name:'Object',exact:true}).click();assert.equal(await page.locator('.classic-popup').getByRole('menuitem',{name:'Outer Shape and Dimensions',exact:true}).count(),0);await page.keyboard.press('Escape');await menuWindow.locator('[data-control=close]').click();
 await page.locator('#desktop-icons [data-action=cad]').click();menuWindow=page.locator('.cad-window');await menuWindow.locator('.cad-controls:not([inert])').waitFor();await command(page,menuWindow,'Object','Outer Shape and Dimensions');assert.equal(await page.locator(':focus').getAttribute('name'),'outertype');await menuWindow.locator('[data-control=close]').click();
 const upload=async(name,body)=>page.evaluate(async({name,body})=>{const r=await fetch('/api/files/upload?'+new URLSearchParams({name}),{method:'POST',body});if(!r.ok)throw Error(await r.text());return(await r.json()).id;},{name,body});
 const logid=await upload('measurements.log','INFO old sample\n'.repeat(90000)+'WARN sensor warm\nERROR sensor failed\nINFO latest sample\n');
 const codeid=await upload('hello.ino','void setup() {}\nvoid loop() {}\n');
 const zipid=await page.evaluate(async id=>{const zip=await(await fetch('/api/files/archive?ids='+id)).blob();const response=await fetch('/api/files/upload?name=sample.zip',{method:'POST',body:zip});return(await response.json()).id;},codeid);
 const form=()=>page.locator('.utility-form');
 async function pick(id){await form().locator('[name=file]').selectOption(id);await form().getByRole('button',{name:'Open',exact:true}).click();await form().waitFor({state:'hidden'});}
 async function download(win,group,label){const promise=page.waitForEvent('download');await command(page,win,group,label);const d=await promise;return {name:d.suggestedFilename(),bytes:await fs.readFile(await d.path())};}
 await page.locator('#desktop-icons [data-action=network]').click();let w=page.locator('.network-window');await w.waitFor();
 await w.locator('.network-name').fill('Pi loopback');await w.locator('.network-host').fill('localhost');await w.locator('.network-port').fill(installed?'8765':'18765');await w.getByRole('button',{name:'Save Target',exact:true}).click();await w.locator('tbody tr').filter({hasText:'Pi loopback'}).waitFor();
 await w.getByRole('button',{name:'DNS Lookup',exact:true}).click();await w.locator('.network-output').filter({hasText:'127.0.0.1'}).waitFor();await w.getByRole('button',{name:'Check TCP Port',exact:true}).click();await w.locator('.network-output').filter({hasText:'OPEN'}).waitFor();
 await w.getByRole('button',{name:'Ping',exact:true}).click();await w.locator('.network-output').filter({hasText:'0% packet loss'}).waitFor();assert.match((await download(w,'File','Save Results')).bytes.toString(),/PING/);
 await command(page,w,'View','Start Monitoring');await w.locator('.app-status').filter({hasText:'every 15 seconds'}).waitFor();await command(page,w,'View','Stop Monitoring');await page.screenshot({path:'/tmp/pi2000-network-tools.png'});await w.locator('[data-control=close]').click();
 await page.locator('#desktop-icons [data-action=archive]').click();w=page.locator('.archive-window');await w.getByRole('button',{name:'Open Archive',exact:true}).click();await pick(zipid);await w.getByRole('checkbox',{name:'Extract hello.ino',exact:true}).check();await w.getByRole('button',{name:'Extract Selected',exact:true}).click();await form().locator('[name=name]').fill('Extracted Sketch');await form().getByRole('button',{name:'Extract',exact:true}).click();await form().waitFor({state:'hidden'});await w.locator('.app-status').filter({hasText:'Extracted 1 files'}).waitFor();
 const items=await page.evaluate(async()=>(await(await fetch('/api/files')).json()).items);const folder=items.find(x=>x.name==='Extracted Sketch');assert.ok(items.some(x=>x.parent===folder.id&&x.name==='hello.ino'));
 await command(page,w,'File','Create Archive');await form().locator('[name=files]').selectOption(folder.id);const zp=page.waitForEvent('download');await form().getByRole('button',{name:'Download ZIP',exact:true}).click();const z=await zp;assert.equal((await fs.readFile(await z.path())).readUInt32LE(0),0x04034b50);await form().waitFor({state:'hidden'});await page.screenshot({path:'/tmp/pi2000-archive-manager.png'});await w.locator('[data-control=close]').click();
 await page.locator('#desktop-icons [data-action=logviewer]').click();w=page.locator('.log-window');await w.getByRole('button',{name:'Open Local Log',exact:true}).click();await pick(logid);await w.locator('.log-summary').filter({hasText:'Latest 256 KB'}).waitFor();await w.locator('.log-level').selectOption('error');assert.equal(await w.locator('.log-line.error').count(),1);assert.match((await download(w,'File','Save Filtered Log')).bytes.toString(),/^ERROR sensor failed$/);
 await w.locator('.log-level').selectOption('all');await w.locator('.log-filter').fill('sensor');assert.equal(await w.locator('.log-line').count(),2);await w.getByRole('button',{name:'Start Following',exact:true}).click();await w.locator('.app-status').filter({hasText:'Following every 5 seconds'}).waitFor();await w.getByRole('button',{name:'Stop Following',exact:true}).click();
 if(!installed){await w.getByRole('button',{name:'Open SSH Log',exact:true}).click();await form().locator('[name=password]').fill('ssh-test-password');await form().locator('[name=path]').fill('/hello.py');await form().getByRole('button',{name:'Open Log',exact:true}).click();await form().waitFor({state:'hidden'});await w.locator('.log-filter').fill('');await w.locator('.log-lines').filter({hasText:'remote original'}).waitFor();}
 await page.screenshot({path:'/tmp/pi2000-log-viewer.png'});await w.locator('[data-control=close]').click();
 await page.locator('#desktop-icons [data-action=displaystudio]').click();w=page.locator('.display-window');await command(page,w,'View','Display Settings');await form().locator('[name=name]').fill('240 Round Test');await form().getByRole('button',{name:'Apply',exact:true}).click();await form().waitFor({state:'hidden'});
 await command(page,w,'Object','Add Rectangle');for(const [name,value] of [['x','0'],['y','0'],['w','240'],['h','240'],['fill','#ff0000'],['stroke','#ff0000']]){await w.locator('.display-properties [name='+name+']').fill(value);await w.locator('.display-properties [name='+name+']').dispatchEvent('change');}
 const raw=await download(w,'File','Export RGB565');assert.equal(raw.bytes.length,240*240*2);assert.equal(raw.bytes.readUInt16LE(0),0);assert.equal(raw.bytes.readUInt16LE((120*240+120)*2),0xf800);
 const png=await download(w,'File','Export PNG');assert.equal(png.bytes.readUInt32BE(16),240);assert.equal(png.bytes.readUInt32BE(20),240);
 const header=await download(w,'File','Export Arduino Header');assert.match(header.bytes.toString(),/uint16_t display_240_Round_Test_pixels\[\] PROGMEM/);await fs.writeFile('/tmp/pi2000-display-export.h',header.bytes);
 await command(page,w,'Object','Add Text');await w.locator('[name=text]').fill('Pi-2000\nDisplay Studio');await w.locator('[name=text]').dispatchEvent('change');await w.getByRole('button',{name:'Save Display',exact:true}).click();await form().getByRole('button',{name:'Save',exact:true}).click();await form().waitFor({state:'hidden'});await w.locator('.app-status').filter({hasText:/^Saved/}).waitFor();
 await command(page,w,'Edit','Duplicate Layer');assert.equal(await w.locator('.display-layer-list option').count(),3);await w.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await w.locator('.display-layer-list option').count(),2);await w.getByRole('button',{name:'Save Display',exact:true}).click();await w.locator('.app-status').filter({hasText:/^Saved/}).waitFor();await page.screenshot({path:'/tmp/pi2000-display-studio.png'});
 await w.locator('[data-control=close]').click();await page.locator('#desktop-icons [data-action=displaystudio]').click();w=page.locator('.display-window');await w.getByRole('button',{name:'Open Display',exact:true}).click();
 const option=await form().locator('[name=file] option').filter({hasText:'240 Round Test.display.json'}).getAttribute('value');await pick(option);assert.equal(await w.locator('.display-layer-list option').count(),2);
 await w.getByRole('button',{name:'Import Image',exact:true}).click();await form().locator('[name=image]').setInputFiles({name:'export.png',mimeType:'image/png',buffer:png.bytes});await form().getByRole('button',{name:'Add Image',exact:true}).click();await form().waitFor({state:'hidden'});assert.equal(await w.locator('.display-layer-list option').count(),3);await w.getByRole('button',{name:'Save Display',exact:true}).click();await w.locator('.app-status').filter({hasText:/^Saved/}).waitFor();
 await w.locator('[data-control=close]').click();await page.locator('#desktop-icons [data-action=displaystudio]').click();w=page.locator('.display-window');await w.getByRole('button',{name:'Open Display',exact:true}).click();await pick(option);assert.equal(await w.locator('.display-layer-list option').count(),3);await command(page,w,'View','Actual Size');
 await page.setViewportSize({width:650,height:800});await page.evaluate(()=>document.documentElement.style.setProperty('--personal-font-size','18px'));await page.screenshot({path:'/tmp/pi2000-display-narrow.png'});const stage=await w.locator('.display-stage').boundingBox();assert.ok(stage.width>130);await w.locator('[data-control=close]').click();await page.setViewportSize({width:1400,height:1000});
 if(!installed){
 await page.locator('#desktop-icons [data-action=arduino]').click();w=page.locator('.arduino-window');await command(page,w,'Tools','Select Port');let dialog=page.locator('dialog.arduino-dialog');await dialog.locator('.port-list option').waitFor();await dialog.locator('.port-list').selectOption({index:0});await dialog.getByRole('button',{name:'Use Port',exact:true}).click();await dialog.waitFor({state:'detached'});
 await command(page,w,'Tools','Serial Plotter');dialog=page.locator('dialog.arduino-dialog');await dialog.getByRole('button',{name:'Connect',exact:true}).click();await dialog.locator('.plot-legend').filter({hasText:'temperature'}).waitFor();await page.waitForFunction(()=>Number(document.querySelector('.plot-status').textContent.match(/(\d+) accepted/)?.[1])>20);
 await dialog.getByRole('button',{name:'Pause Capture',exact:true}).click();const before=await dialog.locator('.plot-status').textContent();await page.waitForTimeout(1500);assert.equal(await dialog.locator('.plot-status').textContent(),before);await dialog.getByRole('button',{name:'Resume Capture',exact:true}).click();
 const csvwait=page.waitForEvent('download');await dialog.getByRole('button',{name:'Export CSV',exact:true}).click();const csv=await fs.readFile(await(await csvwait).path(),'utf8');assert.match(csv,/sample,received_seconds,temperature,humidity/);assert.ok(csv.split('\n').length>20);
 await page.screenshot({path:'/tmp/pi2000-serial-plotter.png'});await dialog.getByRole('button',{name:'Disconnect',exact:true}).click();await dialog.getByRole('button',{name:'Close',exact:true}).click();await w.locator('[data-control=close]').click();
 }
 const parser=await page.evaluate(()=>{const host=document.createElement('div');document.body.append(host);const plot=Win2kSerialPlotter.create(host);plot.feed({stream:'test',chunk:'temperature:23.'});plot.feed({stream:'test',chunk:'5 humidity:48\nboot log\n'});const one=host.querySelector('.plot-status').textContent;plot.feed({stream:'test',dropped:true,chunk:'7 humidity:40\ntemperature:25 humidity:50\n'});const two=host.querySelector('.plot-status').textContent;plot.feed({stream:'test',chunk:'temperature:2'});host.querySelector('.plot-clear').click();plot.feed({stream:'test',chunk:'8\ntemperature:29\n'});const cleared=host.querySelector('.plot-status').textContent;const invalid=['1,NaN','1,Infinity','same:1 same:2','x:1e13','alert(1)'].map(Win2kSerialPlotter.parse);plot.destroy();host.remove();return {one,two,cleared,invalid};});assert.match(parser.one,/1 accepted samples/);assert.match(parser.two,/2 accepted samples/);assert.match(parser.cleared,/1 accepted samples/);assert.ok(parser.invalid.every(x=>x===null));
 assert.deepEqual(errors,[]);console.log('PASS Network DNS/TCP/ping/private saves, ZIP create/extract, bounded log filters/SSH, Display save/reopen/undo/RGB565/PNG/header/narrow, '+(installed?'installed HTTPS':'real serial PTY plot/pause/CSV'));
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
