const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
const A='list fixture passphrase 987',B='secret fixture passphrase 654',newA='new list fixture passphrase 777',newB='new secret fixture passphrase 999';
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.PI2000_TEST_CHROMIUM||'/usr/bin/chromium',headless:true});
 try{
  const context=await browser.newContext({viewport:{width:1100,height:850}}),page=await context.newPage(),errors=[],writes=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/vault')&&r.method()==='PUT')writes.push(r.postData());});
  await page.goto(process.env.PI2000_TEST_URL||'http://127.0.0.1:18765');await page.locator('#login-form [name=password]').fill('browser-test-password');await page.locator('#login-form [type=submit]').click();await page.locator('#session').waitFor({state:'visible'});
  await page.evaluate(()=>Pi2000Shell.actions.vault());const w=page.locator('.vault-window');await w.getByRole('heading',{name:'Create your private Pi-Vault'}).waitFor();
  async function setPair(a=A,b=B){for(const [name,value] of Object.entries({newA:a,repeatA:a,newB:b,repeatB:b}))await w.locator('[name='+name+']').fill(value);}
  async function unlock(){await w.locator('[name=a]').fill(A);await w.getByRole('button',{name:'Unlock List',exact:true}).click();await w.locator('.vault-filters').waitFor();}
  async function bUnlock(value=B){await w.locator('[name=b]').fill(value);await w.getByRole('button',{name:'Unlock Content',exact:true}).click();}
  async function menu(name,item){await w.locator('.classic-menubar').getByRole('menuitem',{name,exact:true}).click();await page.locator('.classic-popup').getByRole('menuitem',{name:item,exact:true}).click();}
  await setPair();await w.getByRole('button',{name:'Create Pi-Vault',exact:true}).click();await w.getByRole('heading',{name:'Save your recovery key'}).waitFor({timeout:60000});
  const recovery=await w.getByRole('textbox',{name:'Recovery key',exact:true}).inputValue();assert.match(recovery,/^PV1-[a-f0-9]{64}$/);await w.getByRole('button',{name:'I Have Saved My Key'}).click();
  await w.locator('[name=a]').fill(B);await w.getByRole('button',{name:'Unlock List',exact:true}).click();await w.locator('.vault-message').filter({hasText:'Incorrect password A'}).waitFor();await unlock();
  async function create(title,secret,category='Password'){await w.getByRole('button',{name:'New Entry',exact:true}).click();await bUnlock();await w.locator('[name=title]').waitFor();await w.locator('[name=title]').fill(title);await w.locator('[name=category]').selectOption(category);await w.getByRole('button',{name:'Show Secret',exact:true}).click();await w.locator('[name=secret]').fill(secret);await w.locator('[name=notes]').fill('private-note-fixture');await w.getByRole('button',{name:'Save and Close',exact:true}).click();await w.locator('.vault-filters').waitFor();}
  await create('Router private title','router-secret-fixture');await create('API private title','api-secret-fixture','API key');
  await w.locator('[name=category]').selectOption('API key');assert.equal(await w.locator('tbody .vault-title').count(),1);await w.locator('[name=category]').selectOption('');await w.locator('[name=search]').fill('Router');assert.equal(await w.locator('tbody .vault-title').count(),1);await w.locator('[name=search]').fill('');
  assert.ok(writes.length===3);for(const data of writes)for(const text of [A,B,recovery,'Router private title','API private title','router-secret-fixture','api-secret-fixture','private-note-fixture'])assert.ok(!data.includes(text),'plaintext leaked into request');
  const stored=await page.evaluate(async()=>{const r=await fetch('/api/vault',{headers:{'X-Vault-Owner':String(Pi2000Desktop.getUser().id)}});return r.json();});
  // Actual cryptographic separation, authentication tags and entry binding.
  const cryptoChecks=await page.evaluate(async({v,A,B})=>{const c=PiVaultCrypto,a=await c.unlock(v,'a',A),b=await c.unlock(v,'b',B),list=await c.readIndex(v,a);let separated=false,tampered=false,swapped=false;try{await c.readEntry(v,a,list.items[0].id);}catch{separated=true;}const bad=structuredClone(v);bad.entries[list.items[0].id].data='AAAA'+bad.entries[list.items[0].id].data.slice(4);try{await c.readEntry(bad,b,list.items[0].id);}catch{tampered=true;}const other=structuredClone(v);other.entries[list.items[0].id]=other.entries[list.items[1].id];try{await c.readEntry(other,b,list.items[0].id);}catch{swapped=true;}return {separated,tampered,swapped};},{v:stored.vault,A,B});assert.deepEqual(cryptoChecks,{separated:true,tampered:true,swapped:true});
  await w.getByRole('button',{name:'Router private title',exact:true}).click();await w.getByRole('button',{name:'Open Entry',exact:true}).click();await bUnlock(A);await w.locator('.vault-message').filter({hasText:'Incorrect password B'}).waitFor();await bUnlock();await w.locator('[name=secret]').waitFor({state:'attached'});assert.equal(await w.locator('[name=secret]').isVisible(),false);await w.getByRole('button',{name:'Show Secret',exact:true}).click();assert.equal(await w.locator('[name=secret]').inputValue(),'router-secret-fixture');
  await w.getByRole('button',{name:'Close Entry',exact:true}).click();assert.equal(await w.locator('[name=secret]').count(),0);await w.getByRole('button',{name:'Open Entry',exact:true}).click();assert.equal(await w.locator('[name=b]').inputValue(),'');await bUnlock();await w.locator('[name=secret]').waitFor({state:'attached'});
  await page.clock.install();await page.clock.fastForward(31000);await w.locator('.vault-filters').waitFor();assert.equal(await w.locator('[name=secret]').count(),0);await w.getByRole('button',{name:'Open Entry',exact:true}).click();await w.locator('[name=b]').waitFor();await w.getByRole('button',{name:'Close Entry',exact:true}).click();
  await w.getByRole('button',{name:'Open Entry',exact:true}).click();await w.locator('[name=b]').fill(B);
  await page.evaluate(()=>{document.querySelector('.vault-form').requestSubmit();[...document.querySelectorAll('.vault-toolbar button')].find(b=>b.textContent==='Lock Pi-Vault').click();});
  await w.locator('[name=a]').waitFor();assert.equal(await w.locator('[name=secret]').count(),0);await unlock();
  await w.getByRole('button',{name:'Router private title',exact:true}).click();await w.getByRole('button',{name:'Open Entry',exact:true}).click();await bUnlock();await w.locator('[name=notes]').fill('edited-private-note-fixture');await w.getByRole('button',{name:'Save and Close',exact:true}).click();await w.locator('.vault-filters').waitFor();
  // Conflict keeps the server's current encrypted snapshot and locks stale UI.
  await page.evaluate(async()=>{const h={'Content-Type':'application/json','X-Vault-Owner':String(Pi2000Desktop.getUser().id)},r=await(await fetch('/api/vault',{headers:h})).json();await fetch('/api/vault',{method:'PUT',headers:{...h,'If-Match':String(r.revision)},body:JSON.stringify(r.vault)});});
  await page.clock.fastForward(6000);await w.locator('[name=a]').waitFor();await unlock();
  await menu('File','Export Encrypted');const downloaded=page.waitForEvent('download');await bUnlock();const exportFile=await downloaded;await exportFile.saveAs(path.join(process.env.PI2000_TEST_ARTIFACTS||'/tmp','vault-encrypted.json'));await w.locator('.vault-filters').waitFor();
  await page.screenshot({path:path.join(process.env.PI2000_TEST_ARTIFACTS||'/tmp','vault-list.png')});
  await menu('Security','Change Passwords');await w.locator('[name=a]').fill(A);await w.locator('[name=b]').fill(B);await setPair(newA,newB);await w.getByRole('button',{name:'Change Passwords',exact:true}).click();await w.getByRole('heading',{name:'Save your recovery key'}).waitFor();const nextRecovery=await w.getByRole('textbox',{name:'Recovery key',exact:true}).inputValue();assert.notEqual(nextRecovery,recovery);await w.getByRole('button',{name:'I Have Saved My Key'}).click();
  await menu('Security','Recovery');await w.locator('[name=code]').fill(nextRecovery);await setPair();await w.getByRole('button',{name:'Recover Pi-Vault',exact:true}).click();await w.getByRole('heading',{name:'Save your recovery key'}).waitFor();await w.getByRole('button',{name:'I Have Saved My Key'}).click();await unlock();
  await menu('File','Import Encrypted');await w.locator('[name=file]').setInputFiles(path.join(process.env.PI2000_TEST_ARTIFACTS||'/tmp','vault-encrypted.json'));await w.locator('[name=a]').fill(A);await w.locator('[name=b]').fill(B);await w.locator('[name=confirm]').check();await w.getByRole('button',{name:'Import Pi-Vault',exact:true}).click();await w.getByRole('button',{name:'Unlock List',exact:true}).waitFor();await unlock();
  await w.getByRole('button',{name:'API private title',exact:true}).click();await menu('Edit','Delete Entry');page.once('dialog',dialog=>dialog.accept());await bUnlock();await w.locator('.vault-filters').waitFor();assert.equal(await w.locator('tbody .vault-title').count(),1);
  await page.clock.fastForward(300001);await w.locator('[name=a]').waitFor();await unlock();
  const broadcast=await context.newPage();await broadcast.goto(process.env.PI2000_TEST_URL||'http://127.0.0.1:18765');await broadcast.locator('#session').waitFor({state:'visible'});await w.waitFor({state:'detached'});await broadcast.close();await page.bringToFront();await page.evaluate(()=>Pi2000Shell.actions.vault());await w.locator('[name=a]').waitFor();await unlock();
  await page.setViewportSize({width:650,height:800});await page.evaluate(()=>document.documentElement.style.setProperty('--personal-font-size','18px'));assert.ok(await w.locator('[data-control=close]').isVisible());
  await w.locator('[data-control=min]').click();await page.locator('#tasks').getByRole('button',{name:'Pi-Vault',exact:true}).click();await w.locator('[name=a]').waitFor();await unlock();
  // A cookie/account change cannot write this window's state into another account.
  const other=await page.evaluate(async()=>{let r=await fetch('/api/users',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'vault-other',password:'fixture-other-password'})});if(!r.ok)throw Error(await r.text());r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:'vault-other',password:'fixture-other-password'})});return r.json();});
  await page.clock.fastForward(6000);await w.locator('[name=a]').waitFor();assert.ok(!(await w.textContent()).includes('Router private title'));
  const foreign=await page.evaluate(async({uid})=>{const response=await fetch('/api/vault',{headers:{'X-Vault-Owner':String(uid)}});return response.json();},{uid:other.id});assert.equal(foreign.vault,null);
  await page.reload();await page.locator('#session').waitFor({state:'visible'});await page.evaluate(()=>Pi2000Shell.actions.vault());await page.locator('.vault-window').getByRole('heading',{name:'Create your private Pi-Vault'}).waitFor();assert.equal(await page.locator('.vault-window').getByText('Router private title',{exact:true}).count(),0);
  assert.deepEqual(errors,[]);console.log('PASS Pi-Vault client encryption, A/B separation, tamper detection, CRUD, fresh B after close/timeout, conflict, export/import, rekey/recovery, narrow layout, minimisation and account-switch isolation');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1)});
