#!/bin/sh
set -eu
if [ "$1" = configure ]; then
 . /usr/share/debconf/confmodule
 db_get pi2000web/admin-password; admin_password=$RET
 db_get pi2000web/creator-username; creator_username=$RET
 for question in admin-password admin-password-confirm; do
  db_set "pi2000web/$question" ''
  db_fset "pi2000web/$question" seen false
 done
 unset RET
 db_set pi2000web/setup-requested false
 db_stop
 printf '%s\000%s' "$admin_password" "$creator_username" | /usr/bin/python3 /usr/lib/pi2000web/package_setup.py configure --bootstrap-stdin
 unset admin_password

fi
