#!/bin/sh
set -eu
case "$1" in
 remove|deconfigure)
  if [ -d /run/systemd/system ]; then
   systemctl stop pi2000-web pi2000-admin pi2000-backup.timer pi2000-arduino pi2000-sessions pi2000-phpmyadmin pi2000-terminal pi2000-accounts
   systemctl disable pi2000-web pi2000-admin pi2000-backup.timer pi2000-arduino pi2000-sessions pi2000-phpmyadmin pi2000-terminal pi2000-accounts
  fi
 ;;
esac
